#!/usr/bin/env python3
"""Controlled, isolated UI check for the dead-character successor route.

This creates a current-source save via the public engine death/serialization APIs,
loads it only into a separate Chromium context, and selects an existing visible
adult through the ordinary successor dialog. It is never a normal fresh-save run.
"""
from __future__ import annotations

from datetime import datetime, timezone
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
import base64
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import threading
import time
import zlib

from playwright.sync_api import expect, sync_playwright
from j_browser_support import attach_early_capture, now_utc, provenance, save_latency_sample, validate_build, verify_http_dist


def project_root(path: Path) -> Path:
    for candidate in path.resolve().parents:
        if (candidate / "package.json").is_file() and (candidate / "src").is_dir():
            return candidate
    raise RuntimeError("Cannot find project root")


ROOT = project_root(Path(__file__))
PHASE = ROOT / "reports/v2/20261008-regional-crisis/phase-06"
BUILD = Path(os.environ.get("PLW_BUILD_STATUS", PHASE / "j-build-status.json"))
SUPPORT = PHASE / "j_browser_support.py"
OWNED = [Path(__file__), SUPPORT]
RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + f"-pid{os.getpid()}"
OUT = PHASE / "j-successor-dry-runs" / RUN_ID
SEED = 20261008


def node_fixture() -> dict:
    # The fixture is generated by current source and public engine APIs. Only its
    # controlled lane marks the active character dead and ensures adult candidates.
    code = r'''import { createServer } from 'vite'
import { resolve } from 'node:path'
const root=process.cwd()
const server=await createServer({configFile:resolve(root,'vite.config.ts'),root,server:{middlewareMode:true},appType:'custom'})
try {
  const {createGame,player,die}=await server.ssrLoadModule('/src/engine/simulation.ts')
  const {serialize,deserialize}=await server.ssrLoadModule('/src/services/saveService.ts')
  const state=createGame(20261008)
  state.life.openingSeen=true
  for(const npc of state.npcs) if(npc.isAlive) npc.age=Math.max(18,npc.age)
  const hero=player(state)
  hero.age=17
  die(state,hero,'受控死亡接續 UI fixture')
  const eligible=state.npcs.filter(npc=>npc.isAlive && npc.age>=18)
  if(!eligible.length) throw new Error('No visible adult successor fixture candidate')
  const raw=serialize(state,1791423000000)
  const roundTrip=deserialize(raw).state
  const restored=roundTrip.characters.find(actor=>actor.id===roundTrip.activeCharacterId)
  if(restored.isAlive!==false || restored.deathCause!=='受控死亡接續 UI fixture') throw new Error('Dead active character fixture failed save round trip')
  if(roundTrip.worldSeed!==state.worldSeed || roundTrip.rngState!==state.rngState || roundTrip.worldTime!==state.worldTime) throw new Error('Fixture save changed seed/RNG/time')
  process.stdout.write(JSON.stringify({raw,seed:state.worldSeed,rngState:state.rngState,worldTime:state.worldTime,
    deadCharacterId:state.activeCharacterId,deadCharacterAge:hero.age,deathCause:hero.deathCause,
    adultCandidates:eligible.map(npc=>({id:npc.id,name:npc.name,age:npc.age})),fixtureMethod:'current-source createGame + explicit controlled adult-candidate fixture + public die() + current serialize/deserialize'}))
} finally { await server.close() }
'''
    proc = subprocess.run(["node", "--input-type=module", "-"], input=code, text=True, capture_output=True, cwd=ROOT, timeout=90)
    if proc.returncode:
        raise RuntimeError(f"Controlled fixture generation failed (exit {proc.returncode}): {proc.stderr[-3000:]}")
    lines = [line for line in proc.stdout.splitlines() if line.lstrip().startswith("{")]
    if not lines:
        raise RuntimeError(f"Fixture generator emitted no JSON: {proc.stdout[-3000:]} {proc.stderr[-3000:]}")
    return json.loads(lines[-1])


class QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self, *_args):
        pass

    def do_GET(self):
        if self.path.split("?", 1)[0] == "/favicon.ico":
            self.send_response(204); self.end_headers()
        else:
            super().do_GET()

    def do_HEAD(self):
        if self.path.split("?", 1)[0] == "/favicon.ico":
            self.send_response(204); self.end_headers()
        else:
            super().do_HEAD()


def packed(raw: str) -> dict:
    data = raw.encode()
    return {"encoding": "zlib+base64", "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest(),
            "data": base64.b64encode(zlib.compress(data, 6)).decode()}


def stable_world_fields(save: dict) -> dict:
    return {key: save.get(key) for key in (
        "worldSeed", "rngState", "worldTime", "regionalCrisis", "threat", "settlement", "tiles", "regions")}


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=False)
    build = validate_build(ROOT, BUILD)
    fixture = node_fixture()
    fixture_raw = fixture.pop("raw")
    (OUT / "controlled-dead-save.json").write_text(fixture_raw, encoding="utf-8")
    fixture["saveSha256"] = hashlib.sha256(fixture_raw.encode()).hexdigest()
    fixture["saveBytes"] = len(fixture_raw.encode())

    handler = lambda *args, **kwargs: QuietHandler(*args, directory=str(ROOT / "dist"), **kwargs)
    server = ThreadingHTTPServer(("127.0.0.1", 0), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    url = f"http://127.0.0.1:{server.server_address[1]}"
    status = {"runId": RUN_ID, "status": "IN_PROGRESS", "lane": "CONTROLLED_DEAD_SUCCESSOR_UI",
        "normalFresh": False, "controlledFixture": True, "stateInjectedIntoThisContextOnly": True,
        "startUTC": now_utc(), "sourceBefore": provenance(ROOT, BUILD, OWNED), "buildStatus": build,
        "fixture": fixture, "url": url, "actions": [], "browserErrors": False}
    try:
        status["servedAssets"] = verify_http_dist(ROOT, url, build)
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(executable_path="/usr/bin/chromium", headless=True, args=["--no-sandbox"])
            context = browser.new_context(viewport={"width": 1280, "height": 900}, reduced_motion="reduce")
            page = context.new_page()
            page_errors, console_errors = [], []
            request_failures, http_failures = [], []
            page.on("pageerror", lambda error: page_errors.append(str(error)))
            page.on("console", lambda message: console_errors.append(message.text) if message.type == "error" else None)
            page.on("requestfailed", lambda request: request_failures.append({"url": request.url, "failure": request.failure}))
            page.on("response", lambda response: http_failures.append({"url": response.url, "status": response.status}) if response.status >= 400 else None)
            attach_early_capture(page)
            page.add_init_script(f"(() => {{ if (!localStorage.getItem('oakvale-v1')) localStorage.setItem('oakvale-v1', {json.dumps(fixture_raw)}); }})();")
            page.goto(url, wait_until="domcontentloaded")
            expect(page.locator(".world-map")).to_be_visible(timeout=15000)
            dialog = page.locator("dialog.pixel-window[open]")
            expect(dialog).to_contain_text("選一位居民，接續旅程", timeout=15000)

            # Pause via the actual visible control before the before/after comparison.
            pause = dialog.get_by_role("button", name="暫停時間")
            expect(pause).to_be_visible(timeout=5000)
            pause.click()
            expect(page.locator("dialog.pixel-window[open]").get_by_role("button", name="繼續時間")).to_be_visible()
            status["pauseControlVerified"] = True

            raw_before = page.evaluate("() => localStorage.getItem('oakvale-v1')")
            before = json.loads(raw_before)
            active_before = next(actor for actor in before["characters"] if actor["id"] == before["activeCharacterId"])
            if active_before.get("isAlive") is not False:
                raise AssertionError("Controlled fixture did not load with a dead active character")
            buttons = dialog.locator(".successor-list button")
            candidates = []
            for index in range(buttons.count()):
                button = buttons.nth(index)
                label = button.inner_text()
                match = re.search(r"·\s*(\d+)\s*歲", label)
                if match and int(match.group(1)) >= 18:
                    candidates.append((button, label))
            if not candidates:
                raise AssertionError("Successor dialog showed no visible 18+ adult option")
            button, label = candidates[0]
            id_match = re.search(r"·\s*(\d+)\s*歲", label)
            selected_age = int(id_match.group(1))
            before_world = stable_world_fields(before)
            old_npcs = before.get("npcs", [])
            old_characters = before.get("characters", [])
            old_events = before.get("history", [])
            selected_id = next((npc["id"] for npc in old_npcs if npc.get("name") and npc["name"] in label and npc.get("age") == selected_age), None)
            if selected_id is None:
                raise AssertionError(f"Visible candidate could not be tied to an existing NPC: {label}")

            button.click()
            expect(page.locator("dialog.pixel-window[open]")).to_have_count(0, timeout=8000)
            page.wait_for_function("id => { const s=JSON.parse(localStorage.getItem('oakvale-v1')||'{}'); return s.activeCharacterId===id; }", arg=selected_id, timeout=10000)
            raw_after = page.evaluate("() => localStorage.getItem('oakvale-v1')")
            after = json.loads(raw_after)
            after_world = stable_world_fields(after)
            mismatches = {key: {"before": before_world[key], "after": after_world[key]}
                          for key in before_world if before_world[key] != after_world[key]}
            expected_npcs = [npc for npc in old_npcs if npc.get("id") != selected_id]
            unrelated_npc_roster_preserved = expected_npcs == after.get("npcs", [])
            selected = next((actor for actor in after.get("characters", []) if actor.get("id") == selected_id), None)
            dead_retained = next((actor for actor in after.get("characters", []) if actor.get("id") == before["activeCharacterId"]), None)
            expected_characters = old_characters + [selected] if selected else old_characters
            character_roster_valid = after.get("characters", []) == expected_characters
            appended_history = after.get("history", [])[len(old_events):]
            sequence_delta_matches_history = after.get("eventSequence", 0) - before.get("eventSequence", 0) == len(appended_history)
            successor_event = sequence_delta_matches_history and any(
                event.get("type") == "character.successor" and "接續了旅程" in event.get("message", "")
                for event in appended_history)
            result = {"verified": not mismatches and unrelated_npc_roster_preserved and character_roster_valid
                and selected is not None and selected.get("isAlive") is True and dead_retained is not None
                and dead_retained.get("isAlive") is False and successor_event,
                "selectedVisibleLabel": label, "selectedNpcId": selected_id, "selectedAge": selected_age,
                "worldFieldsBeforeAfter": {key: {"before": before_world[key], "after": after_world[key]} for key in before_world},
                "worldMismatches": mismatches, "unrelatedNpcRosterPreserved": unrelated_npc_roster_preserved,
                "characterRosterValid": character_roster_valid, "deadCharacterRetained": bool(dead_retained and dead_retained.get("isAlive") is False),
                "successorEventObserved": successor_event, "activeCharacterIdAfter": after.get("activeCharacterId"),
                "fullSaveBefore": packed(raw_before), "fullSaveAfter": packed(raw_after)}
            status["actions"].append({"atUTC": now_utc(), "action": "visible_select_existing_adult_successor",
                "controlledFixture": True, "visible": True, "stateInjected": False, "result": result})
            if not result["verified"]:
                raise AssertionError(f"Successor continuity validation failed: {json.dumps(result, ensure_ascii=False)[:2500]}")
            status["saveLatency"] = save_latency_sample(page)
            status["pageErrors"] = page_errors
            status["consoleErrors"] = console_errors
            status["requestFailures"] = request_failures
            status["httpFailures"] = http_failures
            if page_errors or console_errors or request_failures or http_failures or status["saveLatency"].get("storageErrors") or status["saveLatency"].get("unhandledRejections"):
                raise AssertionError("Browser/storage error signal observed")
            browser.close()
        status["sourceAfter"] = provenance(ROOT, BUILD, OWNED)
        status["sourceStableDuringRun"] = status["sourceBefore"] == status["sourceAfter"]
        if not status["sourceStableDuringRun"]:
            raise AssertionError("Source/build/QA provenance changed during controlled successor UI run")
        status["status"] = "PASS_CONTROLLED_SUCCESSOR_UI"
    except Exception as exc:
        status["status"] = "FAILED"
        status["error"] = f"{type(exc).__name__}: {exc}"
        status["pageErrors"] = status.get("pageErrors", [])
        status["consoleErrors"] = status.get("consoleErrors", [])
        try:
            if 'page' in locals(): page.screenshot(path=str(OUT / "failure.png"), full_page=True)
        except Exception: pass
        try: status["sourceAfter"] = provenance(ROOT, BUILD, OWNED)
        except Exception as prov_exc: status["sourceAfterError"] = str(prov_exc)
    finally:
        server.shutdown(); server.server_close(); thread.join(timeout=3)
        status["endUTC"] = now_utc()
        (OUT / "status.json").write_text(json.dumps(status, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(json.dumps({"status": status["status"], "runId": RUN_ID, "out": str(OUT),
            "error": status.get("error"), "result": status.get("actions", [])[-1].get("result") if status.get("actions") else None,
            "sourceStableDuringRun": status.get("sourceStableDuringRun")}, ensure_ascii=False, indent=2))
    return 0 if status["status"] == "PASS_CONTROLLED_SUCCESSOR_UI" else 1


if __name__ == "__main__":
    raise SystemExit(main())
